### ISSUE TITLE
Few errors: iced version not supported & coc-source

### ISSUE THREAD

**Issue by kkharji** [liquidz/vim-iced-coc-source#2]
Hay there, I've been looking all week for a chance to try out your awesome env setup with clojure and vim. 

I use nvim and dein plugin manager, I've added vim-sexp, vim-iced, and vim-iced-coc-source but no completion. 

When I open a new file I get iced-coc-source: vim-iced v0.11.1 or later is required.
Also, in coc settings I get: Property coc.source.iced.enable is not allowed

Thanks

**Comment by liquidz** [comment]
@tami5 Thanks for your reporting!

> Also, in coc settings I get: Property coc.source.iced.enable is not allowed

It seems that vim-iced-coc-source is not loaded correctly

I'm using this source with the following vim-plug's setting and works well.
https://github.com/liquidz/dotfiles/blob/21d5c3e52221b2ad1a198775482b1e428fa131ab/.vim/conf.d/000-plugin.vim#L71-L76

Could you tell me your dein's settings?

**Comment by kkharji** [comment]
Yah,
```
- { repo: liquidz/vim-iced, on_ft: clojure, hook_source: source $VIM_PATH/plugins/vim-iced.vim }
- { repo: liquidz/vim-iced-coc-source, on_ft: clojure }
```
I'm using yaml for defining plugins but these are the dein settings. I managed to get it working by copying the files to my runtimepath

**Comment by liquidz** [comment]
Thanks! I'll try to reproduce

**Comment by kkharji** [comment]
I've been playing around for few hours, and I got to see it amazing work, I love it a lot!. Thank you for producing such an amazing tool. Its way better then cider & emacs. Wish you all the best. BTW, great docs

**Comment by liquidz** [comment]
That's so great to hear!
If documents lacks some steps to set up coc-source, please let me know 😃
