### ISSUE TITLE
Vim-iced v0.11.1 or later is required.

### ISSUE THREAD

**Issue by D00mch** [liquidz/vim-iced-coc-source#3]
Same issue as [here](https://github.com/liquidz/vim-iced-coc-source/issues/2).
I've found out this problem when I was removing clojure-highlight plugin.
I had the line in my .vimrc
`autocmd BufRead *.clj try | silent! Require | catch /^Fireplace/ | endtry`
and when I removed it I started getting the error. So I have this [crutch-solution](https://github.com/Liverm0r/dotfiles/commit/3bc79660ec15ed11983694c6947809e87137d6f7) (my dotfiles) to get rid of the error.

I install plugins with vim native support (.vim/pack/vendor/start). I just [added](https://github.com/Liverm0r/dotfiles/blob/master/.gitmodules) vim-iced and vim-iced-coc-source as submodules.

**Comment by D00mch** [comment]
Seems like the plugin isn't working, this thing 
`autocmd BufRead *.clj try | silent! Require | catch /^Fireplace/ | endtry`
 was just silencing it.

**Comment by D00mch** [comment]
The problem was in plugins loading order.
I managed to solve it by [lazy-loading](https://gist.github.com/manasthakur/ab4cf8d32a28ea38271ac0d07373bb53#lazy-loading-plugins-using-vim-8-packages) this plugin.

**Comment by liquidz** [comment]
@Liverm0r Sorry for late reply.
I'll add a note for loading order.
