### ISSUE TITLE
Autocompletion not working in stdout buffer

### ISSUE THREAD

**Issue by Cnly** [liquidz/vim-iced-coc-source#4]
As the title suggests... I tried `:CocOpenLog` and saw the stdout buffer is not attached, so I took a look at coc's source and tried to make the buffer attached by `:set buftype=`. But even after that there's no completion popup in the stdout buffer. Is this an intended behaviour? I'm not sure where to look next.

**Comment by liquidz** [comment]
@Cnly Hmm, the file type for stdout buffer is `clojure`, so it should work... I'll have a look this weekend.

**Comment by liquidz** [comment]
@Cnly Sorry for late reaction.
I found the cause:
coc.nvim does not work in buffers which buftype is 'nofile'.
https://github.com/neoclide/coc.nvim/blob/master/history.md#2018-08-16

I patched a workaround to vim-iced not vim-iced-coc-source.
https://github.com/liquidz/vim-iced/commit/b9663858cd617a41390da95ca43d38c477bfa420
Could you try [dev](https://github.com/liquidz/vim-iced/tree/dev) branch in vim-iced?

**Comment by Cnly** [comment]
Hi @liquidz, many thanks for looking into this! The `dev` branch of vim-iced is working for me. Sorry I didn't realise this is to be fixed in vim-iced.

**Comment by liquidz** [comment]
@Cnly Thanks for your confirmation!
I just released v3.7.2 https://github.com/liquidz/vim-iced/pull/375
